add docs on running ecs tasks on k3d
localstack/docs pull request #1235
Opened 2024-05-02 07:20 UTC by HarshCasper

2024-05-03 15:25 UTC, pinzon approved these changes

2024-05-03 17:20 UTC, simonrw requested changes
Thanks for writing this up but there are some simplifications we can make. I will give more info when I am back at my computer

2024-05-03 17:20 UTC, simonrw commented on content/en/user-guide/aws/ecs/index.md
> +You can import the LocalStack image to the Kubernetes cluster by running the following command:
This is not needed for most people. We only do it in the pipeline to make sure we don't pull the public image

2024-05-03 17:20 UTC, simonrw commented on content/en/user-guide/aws/ecs/index.md
> +$ helm upgrade --install localstack localstack/localstack \
This can be simplified tbd

2024-05-09 09:47 UTC, simonrw commented on content/en/user-guide/aws/ecs/index.md
> +$ helm upgrade --install localstack localstack/localstack \
Implemented in bcaa67a9c0700e930bde94a592da32cfd5a10674

2024-05-09 09:48 UTC, simonrw approved these changes
I have implemented my suggestions in bcaa67a9c0700e930bde94a592da32cfd5a10674

2024-05-09 09:50 UTC, simonrw commented on content/en/user-guide/aws/ecs/index.md
> +LocalStack Enterprise image allows you to run ECS tasks on Kubernetes. The tasks are added to ELB load balancer target groups. You can do so by setting the `ECS_TASK_EXECUTOR` environment variable to
```suggestion
LocalStack Enterprise image allows you to run ECS tasks on Kubernetes. The tasks are added to ELB load balancer target groups.
You can do so by setting the `ECS_TASK_EXECUTOR` environment variable to `kubernetes` in the LocalStack container.
```

2024-05-09 09:50 UTC, simonrw commented on content/en/user-guide/aws/ecs/index.md
> +You can now install LocalStack in the Kubernetes cluster by using LocalStack's Helm chart. The following command installs LocalStack with the `kubernetes` executor for ECS and sets the `LOCALSTACK_AU
```suggestion
You can now install LocalStack in the Kubernetes cluster by using LocalStack's Helm chart.
The following command installs LocalStack with the `kubernetes` executor for ECS and sets the `LOCALSTACK_AUTH_TOKEN` environment variable:
```

2024-05-09 11:04 UTC, merged