add example reference to gitlab documentation page
localstack/docs pull request #1377
Opened 2024-07-13 00:21 UTC by tinyg210

Add link to the tutorial with a demo project in the GitLab CI documentation page

2024-07-15 07:46 UTC, HarshCasper requested changes
Please create a section called as `Examples` and add the link over there. For reference — https://docs.localstack.cloud/user-guide/aws/lambda/#examples

2024-07-15 11:33 UTC, remotesynth approved these changes

2024-07-16 02:04 UTC, tinyg210 commented
I understand the desire to keep the pattern and have an Examples section, but I also want to keep it at the top, where it's visible and easily accessible.

2024-07-23 16:21 UTC, HarshCasper approved these changes

2024-07-23 16:21 UTC, merged