DevContainers documentation
localstack/docs pull request #1445
Opened 2024-08-21 08:15 UTC by lakkeger

# Motivation
By adding the DevContainers Feature and Templates to the community index we need a detailed official documentation how to use them.

# Changes
- dind template docs with cli
- dind template docs with VSCode
- dood template docs with cli
- dood template docs with VSCode
- feature docs
- reference pages
- issue warning with VSCode

2024-08-22 11:21 UTC, HarshCasper requested changes

2024-08-22 11:21 UTC, HarshCasper commented on content/en/user-guide/integrations/devcontainers/index.md
> +and so on.
Can we rather use pointers for these?

2024-08-22 11:21 UTC, HarshCasper commented on content/en/user-guide/integrations/devcontainers/index.md
> +and so on.
Can we use pointers for these?

2024-08-22 11:33 UTC, lakkeger commented on content/en/user-guide/integrations/devcontainers/index.md
> +* https://github.com/localstack/devcontainer-feature
Yes. Using devcontainers is not trivial, referring to the docs of the templates, feature or the official docs themselves can be really useful.

2024-08-26 14:23 UTC, HarshCasper approved these changes

2024-08-26 14:23 UTC, merged