document available eks versions
localstack/docs pull request #1597
Opened 2024-12-15 08:36 UTC by HarshCasper

2024-12-16 15:01 UTC, simonrw commented on content/en/user-guide/aws/eks/index.md
> +| Kubernetes Version | k3s Version       |
I presume this list of supported versions comes from the source code? My concern is keeping this list up to date with the supported versions.

We are already 2 releases behind the current release in both the source code _and_ this table. Is there any way we can keep these two up to date?

2024-12-16 15:01 UTC, simonrw commented on content/en/user-guide/aws/eks/index.md
> +
We should also describe how `$EKS_K3S_IMAGE_TAG` can be used to specify a particular k3s  image tag, which may be different to the k8s version.

2025-02-21 10:16 UTC, dfangl requested changes

2025-02-21 10:16 UTC, dfangl commented on content/en/user-guide/aws/eks/index.md
> +The default version is `1.22`.
The default version is now 1.31

2025-02-21 10:16 UTC, dfangl commented on content/en/user-guide/aws/eks/index.md
> +| Kubernetes Version | k3s Version       |
I agree. I added a script which is able to automatically keep the available versions up to date in our codebase, that can also be used to keep this table up to date. I am however a bit reluctant to add this functionality, as it might be superseded soon. I think we can do another manual update, and automate this in the future!

2025-02-21 10:16 UTC, dfangl commented on content/en/user-guide/aws/eks/index.md
> +| 1.22 (Default)     | v1.22.6-k3s1     |
These versions recently changed, and 1.31 + 1.32 is now available. I will send you the link!

2025-02-24 11:11 UTC, dfangl approved these changes
LGTM! Just two suggested changes to make it clearer what image we are starting - good to merge from my side afterwards.

2025-02-24 11:11 UTC, dfangl commented on content/en/references/configuration.md
> +| `EKS_K3S_IMAGE_REPOSITORY` | `rancher/k3s` (default) | Custom repository of the `k8s/rancher` image used to spin up Kubernetes clusters locally. |
```suggestion
| `EKS_K3S_IMAGE_REPOSITORY` | `rancher/k3s` (default) | Custom repository of the `rancher/k3s` image used to spin up Kubernetes clusters locally. |
```

2025-02-24 11:11 UTC, dfangl commented on content/en/references/configuration.md
> +| `EKS_K3S_IMAGE_TAG` | `v1.31.5-k3s1` (default) | Custom tag of the `k8s/rancher` image used to spin up Kubernetes clusters locally. |
```suggestion
| `EKS_K3S_IMAGE_TAG` | `v1.31.5-k3s1` (default) | Custom tag of the `rancher/k3s` image used to spin up Kubernetes clusters locally. |
```

2025-02-24 11:11 UTC, dfangl commented on content/en/user-guide/aws/eks/index.md
> +| 1.25              | v1.25.16-k3s4    | eks.42             |
I think including the EKS platform version here is fine - but we just mock the return value, it does not really mean anything.

2025-02-24 13:40 UTC, merged