Add note about --no-sign-request in AWS CLI
localstack/docs pull request #297
Opened 2022-10-12 02:08 UTC by cmoralesmx

I added a small paragraph about the known limitation when using `--no-sign-request` with the AWS CLI which prevents the request to be routed to the correct service.

Fixes #237

2022-10-20 10:37 UTC, HarshCasper requested changes
Thanks a lot for working on this. Just some minor nits and I would merge it 👍

2022-10-20 10:37 UTC, HarshCasper commented on content/en/integrations/aws-cli/index.md
> +your requests using the AWS CLI which causes localstack to not be able to route
Please replaced `localstack` with `LocalStack`

2022-10-20 10:37 UTC, HarshCasper commented on content/en/integrations/aws-cli/index.md
> +your request to the correct service.
Can you add a small note of what the limitation is and how should the user address it (maybe by using `awslocal` CLI)

2022-10-20 22:38 UTC, cmoralesmx commented
Do you want me to squash the commits into a single one before merge?

2022-10-21 02:26 UTC, HarshCasper approved these changes

2022-10-21 02:26 UTC, merged