add tutorial on deploying container service on ecs and ecr
localstack/docs pull request #523
Opened 2023-03-19 12:41 UTC by HarshCasper

2023-03-19 18:19 UTC, thrau commented
it seems 4 reviewers may not be necessary, so i removed myself :-) it would probably also be better to involve service owners in tutorials that concern them - i know very little about ECS or ECR

2023-03-21 13:37 UTC, dfangl requested changes
Some concerns about validity of statements / not-used shortcuts.
I haven't actually tried the sample against LS, I assume someone already did :) 
BTW: In general, for markdown + VCS, it's often recommended putting each  sentence on a single line (as only double linebreaks are linebreaks in the rendered markdown anyway). That would have made reviewing / commenting on single lines a tad easier.

2023-03-21 13:37 UTC, dfangl commented on content/en/tutorials/ecs-ecr-container-app/index.md
> +```bash
Please use the `{{ command }}` shortcode to prevent people selecting the `$` when copy-pasting. This is applicable on every ```bash on this page.

2023-03-21 13:37 UTC, dfangl commented on content/en/tutorials/ecs-ecr-container-app/index.md
> +awslocal ecr create-repository --repository-name <REPOSITORY_NAME>
Here, the $ prefix is missing as well.

2023-04-24 08:54 UTC, merged