Update JVM debugging docs
localstack/docs pull request #744
Opened 2023-08-02 13:09 UTC by dominikschubert

This new debugging setup is now compatible with both the legacy and the new provider as well as different Java runtimes.

2023-08-02 20:37 UTC, joe4dev requested changes
Much-needed improvements 📈 👏 

👉 The create-function command needs to be adjusted for Java.

🟢 Otherwise, I tested the setup on macOS and can confirm it works for `java8.al2`, `java11`, and `java17`.

2023-08-02 20:37 UTC, joe4dev commented on content/en/user-guide/tools/lambda-tools/debugging/index.md
> +--role arn:aws:iam::000000000000:role/lambda-role
missing trailing `\`

2023-08-02 20:37 UTC, joe4dev commented on content/en/user-guide/tools/lambda-tools/debugging/index.md
> +The debugger can also act as a server by changing the drop-down "Debugger mode" to "Listen to remote JVM".
This section should also mention that the wait script is not needed here

2023-08-03 08:14 UTC, dominikschubert commented on content/en/user-guide/tools/lambda-tools/debugging/index.md
> +--runtime nodejs16.x \
good catch

2023-08-04 15:46 UTC, joe4dev approved these changes
LGTM now 👍

2023-08-04 16:10 UTC, merged