Migrate removed networking variables
localstack/docs pull request #900
Opened 2023-11-08 22:35 UTC by joe4dev

* Remove/migrate edge variables EDGE_PORT/EDGE_PORT_HTTP/EDGE_BIND_HOST. All write-usages. Few read-usages remain until the respective integration tools are updated to adopt `AWS_ENDPOINT_URL`
* Un-deprecate `USE_SSL` and describe its current usage
* Remove `<SERVICE>_PORT_EXTERNAL`

2023-11-08 22:49 UTC, simonrw requested changes
We need to update usages of e.g. `HOSTNAME_EXTERNAL` and other deprecated variables from the main text as well as the configuration section. There are a few references to `HOSTNAME_EXTERNAL` but we need to replace `LOCALSTACK_HOSTNAME` as well (unless used in a read-only capacity).

In addition, could we make a change to the FAQ entry about "Why can’t my other Docker containers reach LocalStack?"? Perhaps keep the first paragraph, but remove the remaining text and link to the network troubleshooting guide?

2023-11-08 22:49 UTC, simonrw commented on content/en/references/configuration.md
`EDGE_FORWARD_URL` is also not used, perhaps we should remove usage of it?

2023-11-08 22:52 UTC, joe4dev commented on content/en/references/configuration.md
yeah, I was wondering whether that belongs to the legacy edge proxy but let's just remove it in the same go 👍

2023-11-08 23:32 UTC, joe4dev commented
> We need to update usages of e.g. `HOSTNAME_EXTERNAL` and other deprecated variables from the main text as well as the configuration section. There are a few references to `HOSTNAME_EXTERNAL` but we need to replace `LOCALSTACK_HOSTNAME` as well (unless used in a read-only capacity).


Correct, that's quite some usage.
I replace them except for transparent endpoint injection (done in the Lambda PR https://github.com/localstack/docs/pull/899) and LocalStack tools that do not yet support `AWS_ENDPOINT_URL` (I added them to the task list in the decision doc).

> In addition, could we make a change to the FAQ entry about "Why can’t my other Docker containers reach LocalStack?"? Perhaps keep the first paragraph, but remove the remaining text and link to the network troubleshooting guide?

Good suggestion, done 👍

2023-11-08 23:36 UTC, joe4dev commented on content/en/user-guide/aws/elastic-kubernetes-service/index.md
> +By default, ECR returns a `repositoryUri` starting with `localhost.localstack.cloud`, such as: `localhost.localstack.cloud:<port>/<repository-name>`.
@simonrw That's the new default, right?

2023-11-08 23:36 UTC, joe4dev commented on content/en/user-guide/ci/gitlab-ci/index.md
> +<summary>For LocalStack versions before 3.0.0</summary>
looks a bit awkward but probably needed

2023-11-09 09:47 UTC, simonrw commented on content/en/user-guide/aws/elastic-kubernetes-service/index.md
> +By default, ECR returns a `repositoryUri` starting with `localhost.localstack.cloud`, such as: `localhost.localstack.cloud:<port>/<repository-name>`.
Yes this is correct

2023-11-09 09:52 UTC, simonrw approved these changes
Looks great, thanks a lot for taking care of this migration. It's exciting to be able to remove `HOSTNAME_EXTERNAL` and `LOCALSTACK_HOSTNAME` from our docs!

2023-11-09 10:28 UTC, merged