transcribe: add note for support of only audio file transcription
localstack/docs pull request #961
Opened 2023-12-13 11:41 UTC by sannya-singal

2023-12-13 12:52 UTC, viren-nadkarni requested changes
Could you also fix the MKV file format (remove 'video' from it)?

2023-12-13 13:42 UTC, ackdav commented
if we support mp4, why do we only support audio?

2023-12-14 07:04 UTC, sannya-singal commented
> if we support mp4, why do we only support audio?

The initial version was focused to work on audio files only. We need to handle multiple streams for video files. Maybe @viren-nadkarni can give more inputs here who previously worked on developing this.

2023-12-14 08:08 UTC, viren-nadkarni approved these changes

2023-12-14 08:10 UTC, merged